### ISSUE TITLE
Upgrade path from Veams Core 5.0.1

### ISSUE THREAD

**Issue by acontia** [Veams/core#18]
I am working on a project that uses Veams core 5.0.1 (that's what the output of `Veams.base.version` says).

Is there any upgrade path to use the latest released version v1.1.1?

**Comment by Sebastian-Fitzner** [comment]
Hi @acontia, 

Yes it is a bit confusing with the versioning. Thing is we decided to create the namespace version (`@veams`) and start from there with version one. This included the separation of the build-in plugins in to its own packages. 

That leads to the migration path. Actually it is pretty easy to update your project. All you need is installing the different packages instead of importing them from `veams/lib`. 
Next to that you should be aware of the used helpers. These needs to be imported from the `@veams/helpers` package.

On the component level it is not necessary to import the whole Veams object by having an `import` statement to `app.js` or `app.veams.js`. In the newest version of the component package you can use `context` to have access to your custom veams object, see the migration step of the accordion component: 
https://github.com/Veams/component-accordion/commit/951762f5e5fc94a83dd772ee50bffe928790ba24#diff-d93bb87552f92892e58bd7a09095a1d2R5

I am happy if I can help you out even more. If you can post your app.js (or app.veams.js), I can see what you used so far and provide a better guide to migrate to the latest version.

**Comment by Sebastian-Fitzner** [comment]
Now activity so far. If you have any questions just re-open it.

**Comment by acontia** [comment]
Thanks for clarifying it and for offering your support. We have put this on hold for now, but I will re-open the ticket if we finally decide to move on and upgrade to the latest version.
