### ISSUE TITLE
Current status of VEAMS?

### ISSUE THREAD

**Issue by pablocastrillo1centrica** [Veams/core#21]
What is the current status of VEAMS?
Looks like the project hasn't been updated in the last 2 years, is it no longer maintained?

**Comment by Sebastian-Fitzner** [comment]
Hi @pablocastrillo1centrica, 
You are right, I haven't updated the core itself for a long time. The reason is that the core is stable enough and has currently no priority. I do not have any feature ideas for the core itself as well...  

When talking about the whole eco system of VEAMS I can share some insights about the current development and next steps. 

_Side note:_ 
Personally in the last 1 1/2 years I changed two times my job which leads to less time available for my OSS projects. But I never wanted to abandon these projects.

For example I published a complete rewritten package a couple of months ago: https://github.com/Veams/rx-store.

## Prio 1

I have one large project I want to finalize which provides a base system to build reactive forms from JSON objects and add a state management system to its core.. Here I need to add also some framework specific adapters like a React adapter with its components so that you can immediately use it. 

## Prio 2

After that I want to focus on my problematic kid, the @veams/cli with its generator in place. The CLI itself is flexible in a project scope scaffolding blueprints but not really good in providing different setups. So here I like to add: 
- TypeScript support out-of-the-box for new projects 
- Simple setups for prototypes 
- Library setup
- React setups with SSR support 
- "Multi-step" setup support to combine one setup template with another 

## Not really in focus

**Components**
All components we offer are not really in focus for now. I think it would be great to have react components in place you can install but this is time consuming... I already started with some components for forms which I can publish later on. 

**Plugins**
They are working, so there is no need for now. 

**Blueprints**
Not really important for now. Perhaps I can tackle them in the `Prio 2` task. 

Hope that helps a bit. Feel free to ask any questions!
